name: Run shell scripts

on:
  pull_request:
    branches:
      - 'main'

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run language scripts
      run: |
        set -e
        ./bash_language/00_hello_world.sh || exit 1;
        echo "Bob" | ./bash_language/01_user_input.sh || exit 1;
        ./bash_language/02_variables.sh || exit 1;
        ./bash_language/03_math.sh || exit 1;
        ./bash_language/04_if_else.sh || exit 1;
        ./bash_language/05_for_loops.sh || exit 1;
        ./bash_language/06_functions.sh || exit 1;
        ./bash_language/07_arguments.sh first_arg second_arg || exit 1;
        ./bash_language/08_arrays.sh || exit 1;

    - name: Run chaining scripts
      run: |
        set -e
        ./chaining/01_and.sh || exit 1;
        ./chaining/02_or.sh || exit 1;        

    - name: Run chaining scripts
      run: |
        set -e
        ./redirecting/01_redirect_stdout.sh || exit 1;
        if [[ $(wc -l <matches.txt) -ne 3 ]]; then
          echo "matches.txt should have 3 lines"
          exit 1
        fi
        ./redirecting/02_redirect_stderr.sh || exit 1;
        if [[ $(wc -l <contents.txt) -ne 1 ]]; then
          echo "contents.txt should have 1 lines"
          exit 1
        fi        
        ./redirecting/03_pipe.sh || exit 1;